server:
  port: 8101
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    name: admin
    url: jdbc:mysql://192.168.126.136:3306/shihe?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456